### ISSUE TITLE
Comments on intros to pandas and data wrangling

### ISSUE THREAD

**Issue by paeby** [starcalm/adahomework#1]
Your code is well commented (next time it would be nice to put the comments in "markdown cells", it makes it easier to read the code and the notebook offers really nice text formatting)
The descriptions of the variables in the second exercise of "Data Wrangling" are really complete, however it would have been nice to have plots for the points 2,3 and 4 as well.

**Comment by starcalm** [comment]
Hi thanks for your feedback! 
1. We will use markdown cell for explanations next time!
2. I didn't plot for task 2, 3 and 4 because they don't require a plot in the description, unlike task 1, asking for plots. But yes, it would be better with pie charts to show the percentages. :)
